import jsPDF from 'jspdf';

export function generateReportPDF(
  title: string,
  content: string,
  author: string = 'MicroManus AI'
): Buffer {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = margin;

  // Header bar
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  
  const titleLines = doc.splitTextToSize(title, contentWidth);
  doc.text(titleLines, margin, 15);
  
  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by ${author} · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, 28);
  
  yPos = 45;

  // Body content
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  const paragraphs = content.split('\n');
  
  for (const paragraph of paragraphs) {
    const trimmed = paragraph.trim();
    if (!trimmed) {
      yPos += 4;
      continue;
    }

    // Detect headers (markdown-style)
    if (trimmed.startsWith('## ')) {
      yPos += 6;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(15, 23, 42);
      const headerText = trimmed.replace('## ', '');
      const headerLines = doc.splitTextToSize(headerText, contentWidth);
      
      if (yPos + headerLines.length * 7 > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
      }
      
      doc.text(headerLines, margin, yPos);
      yPos += headerLines.length * 7 + 2;
      
      // Underline
      doc.setDrawColor(99, 102, 241);
      doc.setLineWidth(0.5);
      doc.line(margin, yPos - 1, margin + 40, yPos - 1);
      yPos += 4;
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      continue;
    }

    if (trimmed.startsWith('# ')) {
      yPos += 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      const headerText = trimmed.replace('# ', '');
      const headerLines = doc.splitTextToSize(headerText, contentWidth);
      
      if (yPos + headerLines.length * 8 > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
      }
      
      doc.text(headerLines, margin, yPos);
      yPos += headerLines.length * 8 + 4;
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      continue;
    }

    // Bullet points
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      const bulletText = trimmed.substring(2);
      const bulletLines = doc.splitTextToSize(bulletText, contentWidth - 8);
      
      if (yPos + bulletLines.length * 5.5 > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
      }
      
      doc.setFillColor(99, 102, 241);
      doc.circle(margin + 2, yPos - 1.5, 1, 'F');
      doc.text(bulletLines, margin + 8, yPos);
      yPos += bulletLines.length * 5.5 + 2;
      continue;
    }

    // Regular paragraph
    const lines = doc.splitTextToSize(trimmed, contentWidth);
    
    if (yPos + lines.length * 5.5 > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
    
    doc.text(lines, margin, yPos);
    yPos += lines.length * 5.5 + 3;
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `MicroManus Research Report · Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  return Buffer.from(doc.output('arraybuffer'));
}
